############################
## CHANGE THESE
############################

baseURL: 'https://mfuhrmann.github.io/L1nkr'
title: 'L1nkr'

############################
## MODULES
############################

module:
  imports:
    - path: github.com/mfuhrmann/L1nkr


############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


